services:
  web:
    build: app/aspnetapp
    ports:
      - 80:80
  db:
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: VerySecurePassword01
    image: mcr.microsoft.com/azure-sql-edge:1.0.4
    restart: always
    healthcheck:
        test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P VerySecurePassword01 -Q 'SELECT 1' || exit 1"]
        interval: 10s
        retries: 10
        start_period: 10s
        timeout: 3s
  proxy:
    build: proxy
    ports:
      - 80:80
    depends_on:
      - web